---
version: 2.1

orbs:
  release-management: rkesters/pnpm-release-management@0.0.1

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
              node_version:
                - lts
                - maintenance
  dependabot-automerge:
    triggers:
      - schedule:
          cron: '0 2,5,8,11 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/dependabot-automerge
